# Generated by Django 4.2.6 on 2023-11-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_ticket_ticketanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('0', 'new from user'), ('1', 'seen user message'), ('2', 'new from admin'), ('3', 'seen admin message'), ('4', 'spam')], default='0', max_length=3, verbose_name='status'),
        ),
    ]
