# Generated by Django 4.2.6 on 2023-11-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='attachment',
            field=models.FileField(blank=True, help_text='you can upload image or *.zip file for attachment.', upload_to='tickets/messages/customer_file/', verbose_name='attachment file'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('0', 'new from user'), ('1', 'seen user message'), ('2', 'new from admin'), ('3', 'admin message seen by user'), ('4', 'spam')], default='0', max_length=3, verbose_name='status'),
        ),
    ]
